### ISSUE TITLE
[Mobile] Navigation bar does not deactivate when not active

### ISSUE THREAD

**Issue by thisisclement** [thisisclement/Foundation6#8]
Whenever you click on mobile menu, and you don't click on any of the menu items, when you scroll down it doesn't deactivate

**Comment by thisisclement** [comment]
Might be a foundation bug? Perhaps can use js to deactivate the navigation bar.

**Comment by jaspersorrio** [comment]
What is the intended behaviour?

**Comment by jaspersorrio** [comment]
Added function that removes the banner when scrolled in commit e629dc2

**Comment by thisisclement** [comment]
The expected behaviour is the following:
1) click on menu (menu item appears)
2) did not click on any menu item and decides to scroll
3) the menu should automatically be closed

Does this commit solve that? I only see this issue on **mobile** though.

**Comment by thisisclement** [comment]
I think this commit does deactivate the navigation bar even though on non-mobile views as well. Like the whole bar just disappears and there doesnt seem to have a way to re-activate it. Perhaps kick in this hide function only on mobile devices?
